require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - '*_spec.rb'
    - 'db/schema.rb'
  AllowedMethods: ['describe', 'context']

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

RSpec/NestedGroups:
  Max: 6

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
