require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-rake

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/BlockLength:
  Exclude: 
    - '*_spec.rb'
    - 'test/**/*_test.rb'
    - 'db/schema.rb'
    - 'config/routes.rb'
  CountAsOne:
    - hash

Metrics/ClassLength:
  Max: 150
  CountAsOne:
    - hash

Metrics/MethodLength:
  Max: 25
  Exclude: 
    - '*_test.rb'

Naming/VariableNumber:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/Output:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
