default: &default
  adapter: postgresql
  encoding: utf8
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  # database: <%= ENV['DB_NAME'] %>
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: fabular_dev

test:
  <<: *default
  database: fabular_test

production:
  <<: *default
  database: fabular_production
